### ISSUE TITLE
Crystal Chip HDD support

### ISSUE THREAD

**Issue by saildot4k** [m4x10187/ps2-modchip-files#3]
The Cystal Chip modchips support installing/loading from internal HDD. HOWEVER the documentation does not describe how to do so anywhere outside of the PBAT scripts.

Recommend to document that to install/load from HDD, user needs to create an internal drive partition labeled <code>+Crystal</code>
This is not documented in the release files, the website archive mentions <code>Crystal</code> but this is incorrect.

**Comment by m4x10187** [comment]
Thanks for the suggestion, whenever I get time, I'll add a guide into the repo.
